-- Butler colorscheme. Follows vim.o.background; palette comes from lua/butler/palette.lua
-- (generated from ~/.config/theme/butler/palette.json so tmux/yazi stay in sync).
-- Backgrounds stay transparent: the terminal glass is the page, chrome() in config.appearance
-- paints only the pieces that need a surface.
local p = require("butler.palette")[vim.o.background == "dark" and "dark" or "light"]

vim.cmd.highlight("clear")
if vim.fn.exists("syntax_on") == 1 then
	vim.cmd.syntax("reset")
end
vim.g.colors_name = "butler"
vim.o.termguicolors = true

local none = "NONE"
local hl = function(group, spec)
	vim.api.nvim_set_hl(0, group, spec)
end

local groups = {
	-- editor chrome
	Normal = { fg = p.ice, bg = none },
	NormalNC = { fg = p.ice, bg = none },
	NormalFloat = { fg = p.ice, bg = p.deep },
	FloatBorder = { fg = p.blue, bg = p.deep },
	FloatTitle = { fg = p.glow, bg = p.deep, bold = true },
	Cursor = { fg = p.on_accent, bg = p.cyan },
	CursorLine = { bg = p.deep },
	CursorColumn = { bg = p.deep },
	ColorColumn = { bg = p.deep },
	CursorLineNr = { fg = p.cyan, bold = true },
	LineNr = { fg = p.dim },
	SignColumn = { fg = p.dim, bg = none },
	FoldColumn = { fg = p.dim, bg = none },
	Folded = { fg = p.steel, bg = p.deep, italic = true },
	EndOfBuffer = { fg = p.line },
	VertSplit = { fg = p.line },
	WinSeparator = { fg = p.line },
	Visual = { bg = p.selected },
	VisualNOS = { bg = p.selected },
	Search = { fg = p.on_accent, bg = p.amber },
	IncSearch = { fg = p.on_accent, bg = p.glow },
	CurSearch = { fg = p.on_accent, bg = p.glow },
	Substitute = { fg = p.on_accent, bg = p.coral },
	MatchParen = { fg = p.glow, bg = p.selected, bold = true },
	Pmenu = { fg = p.ice, bg = p.deep },
	PmenuSel = { fg = p.glow, bg = p.selected, bold = true },
	PmenuSbar = { bg = p.panel },
	PmenuThumb = { bg = p.steel },
	WildMenu = { fg = p.on_accent, bg = p.cyan },
	StatusLine = { fg = p.ice, bg = none },
	StatusLineNC = { fg = p.muted, bg = none },
	TabLine = { fg = p.muted, bg = none },
	TabLineFill = { bg = none },
	TabLineSel = { fg = p.ice, bg = p.panel, bold = true },
	WinBar = { fg = p.ice, bg = none },
	WinBarNC = { fg = p.muted, bg = none },
	Title = { fg = p.glow, bold = true },
	Directory = { fg = p.blue, bold = true },
	NonText = { fg = p.line },
	Whitespace = { fg = p.line },
	SpecialKey = { fg = p.steel },
	Conceal = { fg = p.dim },
	Question = { fg = p.mint },
	MoreMsg = { fg = p.mint },
	ModeMsg = { fg = p.cyan, bold = true },
	ErrorMsg = { fg = p.coral, bold = true },
	WarningMsg = { fg = p.amber },
	QuickFixLine = { bg = p.selected },
	SpellBad = { sp = p.coral, undercurl = true },
	SpellCap = { sp = p.amber, undercurl = true },
	SpellLocal = { sp = p.cyan, undercurl = true },
	SpellRare = { sp = p.lavender, undercurl = true },
	DiffAdd = { fg = p.mint, bg = none },
	DiffChange = { fg = p.amber, bg = none },
	DiffDelete = { fg = p.coral, bg = none },
	DiffText = { fg = p.on_accent, bg = p.amber },

	-- syntax (mirrors Pi's syntax* slots)
	-- 注释不用斜体：CJK 字形没有真斜体，合成倾斜后反而更难读
	Comment = { fg = p.comment },
	Constant = { fg = p.amber },
	String = { fg = p.mint },
	Character = { fg = p.mint },
	Number = { fg = p.peach },
	Boolean = { fg = p.peach },
	Float = { fg = p.peach },
	Identifier = { fg = p.ice },
	Function = { fg = p.cyan },
	Statement = { fg = p.violet },
	Conditional = { fg = p.violet },
	Repeat = { fg = p.violet },
	Label = { fg = p.gold },
	Operator = { fg = p.steel },
	Keyword = { fg = p.violet },
	Exception = { fg = p.violet },
	PreProc = { fg = p.peach },
	Include = { fg = p.peach },
	Define = { fg = p.peach },
	Macro = { fg = p.peach },
	PreCondit = { fg = p.peach },
	Type = { fg = p.gold },
	StorageClass = { fg = p.violet },
	Structure = { fg = p.gold },
	Typedef = { fg = p.gold },
	Special = { fg = p.steel },
	SpecialChar = { fg = p.peach },
	Tag = { fg = p.blue },
	Delimiter = { fg = p.muted },
	SpecialComment = { fg = p.steel },
	Debug = { fg = p.coral },
	Underlined = { fg = p.cyan, underline = true },
	Bold = { bold = true },
	Italic = { italic = true },
	Ignore = { fg = p.dim },
	Error = { fg = p.coral, bold = true },
	Todo = { fg = p.on_accent, bg = p.amber, bold = true },

	-- treesitter
	["@variable"] = { fg = p.ice },
	["@variable.builtin"] = { fg = p.coral },
	["@variable.parameter"] = { fg = p.ice, italic = true },
	["@variable.member"] = { fg = p.sky },
	["@constant"] = { fg = p.amber },
	["@constant.builtin"] = { fg = p.peach },
	["@module"] = { fg = p.gold },
	["@string"] = { fg = p.mint },
	["@string.escape"] = { fg = p.peach },
	["@string.special.url"] = { fg = p.cyan, underline = true },
	["@number"] = { fg = p.peach },
	["@boolean"] = { fg = p.peach },
	["@type"] = { fg = p.gold },
	["@type.builtin"] = { fg = p.gold, italic = true },
	["@attribute"] = { fg = p.gold, italic = true },
	["@property"] = { fg = p.sky },
	["@function"] = { fg = p.cyan },
	["@function.builtin"] = { fg = p.glow },
	["@function.call"] = { fg = p.cyan },
	["@function.method"] = { fg = p.cyan },
	["@constructor"] = { fg = p.gold },
	["@operator"] = { fg = p.steel },
	["@keyword"] = { fg = p.violet },
	["@keyword.function"] = { fg = p.violet },
	["@keyword.return"] = { fg = p.violet, italic = true },
	["@keyword.import"] = { fg = p.peach },
	["@keyword.directive"] = { fg = p.peach },
	["@keyword.operator"] = { fg = p.violet },
	["@keyword.conditional"] = { fg = p.violet },
	["@keyword.repeat"] = { fg = p.violet },
	["@keyword.exception"] = { fg = p.violet },
	["@keyword.modifier"] = { fg = p.violet },
	["@keyword.type"] = { fg = p.violet },
	["@type.definition"] = { fg = p.gold },
	["@label"] = { fg = p.gold },
	["@string.regexp"] = { fg = p.peach },
	["@string.special"] = { fg = p.peach },
	["@character"] = { fg = p.mint },
	["@character.special"] = { fg = p.peach },
	["@variable.parameter.builtin"] = { fg = p.coral, italic = true },
	["@lsp.type.keyword"] = { link = "@keyword" },
	["@lsp.type.type"] = { link = "@type" },
	["@lsp.type.class"] = { link = "@type" },
	["@lsp.type.struct"] = { link = "@type" },
	["@lsp.type.interface"] = { link = "@type" },
	["@lsp.type.enum"] = { link = "@type" },
	["@lsp.type.enumMember"] = { link = "@constant" },
	["@lsp.type.function"] = { link = "@function" },
	["@lsp.type.method"] = { link = "@function.method" },
	["@lsp.type.variable"] = { link = "@variable" },
	["@lsp.type.macro"] = { link = "@keyword.directive" },
	["@lsp.mod.readonly"] = { fg = p.amber },
	["@lsp.typemod.variable.defaultLibrary"] = { fg = p.coral },
	["@punctuation.bracket"] = { fg = p.muted },
	["@punctuation.delimiter"] = { fg = p.muted },
	["@punctuation.special"] = { fg = p.steel },
	["@comment"] = { fg = p.comment },
	["@comment.todo"] = { fg = p.on_accent, bg = p.amber, bold = true },
	["@comment.error"] = { fg = p.on_accent, bg = p.coral, bold = true },
	["@comment.warning"] = { fg = p.on_accent, bg = p.amber, bold = true },
	["@comment.note"] = { fg = p.on_accent, bg = p.cyan, bold = true },
	["@tag"] = { fg = p.blue },
	["@tag.attribute"] = { fg = p.gold, italic = true },
	["@tag.delimiter"] = { fg = p.muted },
	["@markup.heading"] = { fg = p.glow, bold = true },
	["@markup.strong"] = { bold = true },
	["@markup.italic"] = { italic = true },
	["@markup.link"] = { fg = p.cyan },
	["@markup.link.url"] = { fg = p.dim, underline = true },
	["@markup.raw"] = { fg = p.mint },
	["@markup.quote"] = { fg = p.steel, italic = true },
	["@markup.list"] = { fg = p.cyan },
	["@diff.plus"] = { fg = p.mint },
	["@diff.minus"] = { fg = p.coral },
	["@diff.delta"] = { fg = p.amber },

	-- lsp
	["@lsp.type.parameter"] = { link = "@variable.parameter" },
	["@lsp.type.property"] = { link = "@property" },
	["@lsp.type.namespace"] = { link = "@module" },
	LspReferenceText = { bg = p.selected },
	LspReferenceRead = { bg = p.selected },
	LspReferenceWrite = { bg = p.selected, underline = true },
	LspInlayHint = { fg = p.dim, bg = none, italic = true },
	LspSignatureActiveParameter = { fg = p.glow, bold = true },
	DiagnosticError = { fg = p.coral },
	DiagnosticWarn = { fg = p.amber },
	DiagnosticInfo = { fg = p.cyan },
	DiagnosticHint = { fg = p.mint },
	DiagnosticOk = { fg = p.mint },
	DiagnosticUnderlineError = { sp = p.coral, undercurl = true },
	DiagnosticUnderlineWarn = { sp = p.amber, undercurl = true },
	DiagnosticUnderlineInfo = { sp = p.cyan, undercurl = true },
	DiagnosticUnderlineHint = { sp = p.mint, undercurl = true },
	DiagnosticVirtualTextError = { fg = p.coral, bg = none, italic = true },
	DiagnosticVirtualTextWarn = { fg = p.amber, bg = none, italic = true },
	DiagnosticVirtualTextInfo = { fg = p.cyan, bg = none, italic = true },
	DiagnosticVirtualTextHint = { fg = p.mint, bg = none, italic = true },

	-- common plugins
	GitSignsAdd = { fg = p.mint },
	GitSignsChange = { fg = p.amber },
	GitSignsDelete = { fg = p.coral },
	TelescopeBorder = { fg = p.blue, bg = none },
	TelescopePromptPrefix = { fg = p.cyan },
	TelescopeSelection = { fg = p.glow, bg = p.selected, bold = true },
	TelescopeMatching = { fg = p.amber, bold = true },
	SnacksPickerBorder = { fg = p.blue, bg = none },
	SnacksPickerMatch = { fg = p.amber, bold = true },
	SnacksIndent = { fg = p.line },
	SnacksIndentScope = { fg = p.steel },
	IblIndent = { fg = p.line },
	IblScope = { fg = p.steel },
	WhichKey = { fg = p.cyan },
	WhichKeyGroup = { fg = p.sky },
	WhichKeyDesc = { fg = p.ice },
	WhichKeySeparator = { fg = p.dim },
	WhichKeyBorder = { fg = p.blue },
	NoiceCmdlinePopupBorder = { fg = p.blue },
	NoiceCmdlineIcon = { fg = p.cyan },
	NotifyINFOBorder = { fg = p.mint },
	NotifyWARNBorder = { fg = p.amber },
	NotifyERRORBorder = { fg = p.coral },
	NotifyINFOTitle = { fg = p.mint },
	NotifyWARNTitle = { fg = p.amber },
	NotifyERRORTitle = { fg = p.coral },
	NotifyINFOIcon = { fg = p.mint },
	NotifyWARNIcon = { fg = p.amber },
	NotifyERRORIcon = { fg = p.coral },
	CmpItemAbbrMatch = { fg = p.amber, bold = true },
	CmpItemAbbrMatchFuzzy = { fg = p.amber },
	CmpItemKindFunction = { fg = p.glow },
	CmpItemKindVariable = { fg = p.ice },
	CmpItemKindKeyword = { fg = p.violet },
	CmpItemKindText = { fg = p.muted },
	BlinkCmpLabelMatch = { fg = p.amber, bold = true },
	BlinkCmpMenuBorder = { fg = p.blue },
	BlinkCmpDocBorder = { fg = p.blue },
	FlashLabel = { fg = p.on_accent, bg = p.coral, bold = true },
	FlashMatch = { fg = p.glow, bg = p.selected },
	LazyH1 = { fg = p.on_accent, bg = p.cyan, bold = true },
	LazyButtonActive = { fg = p.on_accent, bg = p.cyan, bold = true },
	MasonHeader = { fg = p.on_accent, bg = p.cyan, bold = true },
	TroubleNormal = { bg = none },
	NeoTreeNormal = { bg = none },
	NeoTreeNormalNC = { bg = none },
	NeoTreeDirectoryIcon = { fg = p.blue },
	NeoTreeDirectoryName = { fg = p.blue },
	NeoTreeGitModified = { fg = p.amber },
	NeoTreeGitAdded = { fg = p.mint },
	NeoTreeGitDeleted = { fg = p.coral },
	OilDir = { fg = p.blue, bold = true },
	OilFile = { fg = p.ice },
	OilLink = { fg = p.cyan },
	RenderMarkdownCode = { bg = p.deep },
	RenderMarkdownCodeInline = { fg = p.mint, bg = p.deep },
	RenderMarkdownH1Bg = { bg = p.panel },
	RenderMarkdownH2Bg = { bg = p.deep },
	MiniIconsBlue = { fg = p.blue },
	MiniIconsCyan = { fg = p.cyan },
	MiniIconsGreen = { fg = p.mint },
	MiniIconsOrange = { fg = p.amber },
	MiniIconsPurple = { fg = p.violet },
	MiniIconsRed = { fg = p.coral },
	MiniIconsYellow = { fg = p.gold },
	MiniIconsGrey = { fg = p.muted },
	MiniIconsAzure = { fg = p.sky },
}

for group, spec in pairs(groups) do
	hl(group, spec)
end

-- 内嵌终端沿用 Butler 的 16 色映射
vim.g.terminal_color_0 = p.deep
vim.g.terminal_color_8 = p.dim
vim.g.terminal_color_1 = p.coral
vim.g.terminal_color_9 = p.coral
vim.g.terminal_color_2 = p.mint
vim.g.terminal_color_10 = p.mint
vim.g.terminal_color_3 = p.amber
vim.g.terminal_color_11 = p.amber
vim.g.terminal_color_4 = p.blue
vim.g.terminal_color_12 = p.sky
vim.g.terminal_color_5 = p.violet
vim.g.terminal_color_13 = p.violet
vim.g.terminal_color_6 = p.cyan
vim.g.terminal_color_14 = p.glow
vim.g.terminal_color_7 = p.muted
vim.g.terminal_color_15 = p.ice
