#!/usr/bin/env python3
"""Render the Butler palette into Ghostty / herdr / tmux / yazi / nvim / oh-my-posh / delta theme files.

palette.json is the only hand-edited input; every emitted file says so in its
header. Run after editing the palette: `python3 ~/.config/theme/butler/generate.py`.
"""
import json
import os
from pathlib import Path
import math
import re
import sys
from xml.sax.saxutils import escape

HERE = Path(__file__).resolve().parent
CFG = Path(os.path.expanduser("~/.config"))
RAW = json.loads((HERE / "palette.json").read_text())

def derive(c: dict) -> dict:
    """The names the generators below use, taken from the Catppuccin palette: surfaces from base/mantle/surface*, text levels from text/subtext*/overlay*,
    and one hue per accent (cyan = sky, glow = teal, mint = green, coral = red, violet = mauve, gold = yellow, amber = peach, peach = maroon)."""
    mix = lambda front, behind, a: "#%02x%02x%02x" % tuple(round((f * a + b * (1 - a)) * 255) for f, b in zip(_rgb(front), _rgb(behind)))
    return {"bg": c["base"], "panel": c["surface0"], "deep": c["mantle"], "selected": c["surface1"], "line": c["surface2"],
            "ice": c["text"], "steel": c["subtext0"], "muted": c["subtext1"], "dim": c["overlay1"], "comment": c["overlay0"],
            "cyan": c["sky"], "glow": c["teal"], "blue": c["blue"], "sky": c["sapphire"], "lavender": c["lavender"], "mint": c["green"],
            "amber": c["peach"], "coral": c["red"], "on_accent": c["base"], "violet": c["mauve"], "gold": c["yellow"], "peach": c["maroon"],
            "ok_bg": mix(c["green"], c["base"], 0.14), "err_bg": mix(c["red"], c["base"], 0.14)}

HEADER = "generated by ~/.config/theme/butler/generate.py from palette.json — edit the palette, not this file"

def write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text)
    print("wrote", path)

# ---------------------------------------------------------------- tmux
def tmux(mode: str, p: dict) -> str:
    return f"""# Butler {mode} — {HEADER}
# Same bubble layout as the previous Ayu/Catppuccin files; bg=default keeps the terminal glass.

set -g status on
set -g status-position bottom
set -g status-interval 1
set -g status-justify absolute-centre
set -g status-left-style NONE
set -g status-right-style NONE
set -g status-left-length 40
set -g status-right-length 40

set -g status-style "fg={p['muted']},bg=default"
set -g status-bg default

set -g status-left "#[fg={p['panel']},bg=default]#[fg={p['ice']},bg={p['panel']},bold] #S:#I.#P #[fg={p['panel']},bg=default]"
set -g status-right "#[fg={p['panel']},bg=default]#[fg={p['ice']},bg={p['panel']}] #h #[fg={p['panel']},bg=default]"

setw -g window-status-separator " "
setw -g window-status-style "NONE,fg={p['muted']},bg=default"
setw -g window-status-format "#[fg={p['steel']},bg=default]#[fg={p['on_accent']},bg={p['steel']},bold] #I #[fg={p['steel']},bg={p['panel']}]#[fg={p['ice']},bg={p['panel']}] #W #[fg={p['panel']},bg=default]"
setw -g window-status-current-format "#[fg={p['cyan']},bg=default]#[fg={p['on_accent']},bg={p['cyan']},bold] #I #[fg={p['cyan']},bg={p['selected']}]#[fg={p['ice']},bg={p['selected']}] #W #[fg={p['selected']},bg=default]"
setw -g window-status-activity-style "underscore,fg={p['amber']},bg=default"

set -g mode-style "fg={p['ice']},bg={p['selected']}"
set -g message-style "fg={p['ice']},bg={p['panel']}"
set -g message-command-style "fg={p['cyan']},bg={p['panel']}"
set -g pane-border-style "fg={p['line']}"
set -g pane-active-border-style "fg={p['cyan']}"
set -g clock-mode-colour "{p['cyan']}"
set -g clock-mode-style 24
set -g display-panes-active-colour "{p['cyan']}"
set -g display-panes-colour "{p['amber']}"
"""

# ---------------------------------------------------------------- yazi
def yazi_flavor(mode: str, p: dict) -> str:
    return f"""# Butler {mode} flavor — {HEADER}
# Icon colours stay on yazi's built-in {mode} preset; syntax colours come from tmtheme.xml next to this file.
#:schema https://yazi-rs.github.io/schemas/theme.json

[mgr]
cwd = {{ fg = "{p['glow']}", bold = true }}
find_keyword  = {{ fg = "{p['amber']}", bold = true, italic = true, underline = true }}
find_position = {{ fg = "{p['coral']}", bg = "reset", bold = true, italic = true }}
symlink_target = {{ fg = "{p['steel']}", italic = true }}
marker_copied   = {{ fg = "{p['mint']}",  bg = "{p['mint']}" }}
marker_cut      = {{ fg = "{p['coral']}", bg = "{p['coral']}" }}
marker_marked   = {{ fg = "{p['glow']}",  bg = "{p['glow']}" }}
marker_selected = {{ fg = "{p['amber']}", bg = "{p['amber']}" }}
count_copied   = {{ fg = "{p['on_accent']}", bg = "{p['mint']}" }}
count_cut      = {{ fg = "{p['on_accent']}", bg = "{p['coral']}" }}
count_selected = {{ fg = "{p['on_accent']}", bg = "{p['amber']}" }}
border_style = {{ fg = "{p['line']}" }}

[tabs]
active   = {{ fg = "{p['on_accent']}", bg = "{p['cyan']}", bold = true }}
inactive = {{ fg = "{p['cyan']}", bg = "{p['panel']}" }}

[mode]
normal_main = {{ fg = "{p['on_accent']}", bg = "{p['cyan']}", bold = true }}
normal_alt  = {{ fg = "{p['cyan']}", bg = "{p['panel']}" }}
select_main = {{ fg = "{p['on_accent']}", bg = "{p['amber']}", bold = true }}
select_alt  = {{ fg = "{p['amber']}", bg = "{p['panel']}" }}
unset_main  = {{ fg = "{p['on_accent']}", bg = "{p['coral']}", bold = true }}
unset_alt   = {{ fg = "{p['coral']}", bg = "{p['panel']}" }}

[indicator]
parent  = {{ fg = "{p['ice']}", bg = "{p['selected']}" }}
current = {{ fg = "{p['ice']}", bg = "{p['selected']}", bold = true }}
preview = {{ fg = "{p['ice']}", bg = "{p['selected']}" }}

[status]
overall   = {{ fg = "{p['muted']}" }}
perm_sep   = {{ fg = "{p['dim']}" }}
perm_type  = {{ fg = "{p['mint']}" }}
perm_read  = {{ fg = "{p['amber']}" }}
perm_write = {{ fg = "{p['coral']}" }}
perm_exec  = {{ fg = "{p['cyan']}" }}
progress_label  = {{ fg = "{p['ice']}", bold = true }}
progress_normal = {{ fg = "{p['cyan']}", bg = "{p['panel']}" }}
progress_error  = {{ fg = "{p['coral']}", bg = "{p['panel']}" }}

[which]
border          = {{ fg = "{p['blue']}" }}
mask            = {{ bg = "{p['deep']}" }}
cand            = {{ fg = "{p['cyan']}" }}
rest            = {{ fg = "{p['dim']}" }}
desc            = {{ fg = "{p['steel']}" }}
separator_style = {{ fg = "{p['line']}" }}

[confirm]
border  = {{ fg = "{p['blue']}" }}
title   = {{ fg = "{p['glow']}", bold = true }}
body    = {{ fg = "{p['ice']}" }}
list    = {{ fg = "{p['muted']}" }}
btn_yes = {{ fg = "{p['on_accent']}", bg = "{p['cyan']}", bold = true }}
btn_no  = {{ fg = "{p['muted']}" }}

[spot]
border   = {{ fg = "{p['blue']}" }}
title    = {{ fg = "{p['glow']}", bold = true }}
tbl_col  = {{ fg = "{p['cyan']}" }}
tbl_cell = {{ fg = "{p['ice']}", bg = "{p['selected']}" }}

[notify]
title_info  = {{ fg = "{p['mint']}" }}
title_warn  = {{ fg = "{p['amber']}" }}
title_error = {{ fg = "{p['coral']}" }}

[pick]
border   = {{ fg = "{p['blue']}" }}
active   = {{ fg = "{p['glow']}", bg = "{p['selected']}", bold = true }}
inactive = {{ fg = "{p['ice']}" }}

[input]
border   = {{ fg = "{p['blue']}" }}
title    = {{ fg = "{p['glow']}" }}
value    = {{ fg = "{p['ice']}" }}
selected = {{ bg = "{p['selected']}" }}

[cmp]
border   = {{ fg = "{p['blue']}" }}
active   = {{ fg = "{p['glow']}", bg = "{p['selected']}" }}
inactive = {{ fg = "{p['ice']}" }}

[tasks]
border  = {{ fg = "{p['blue']}" }}
title   = {{ fg = "{p['glow']}" }}
hovered = {{ fg = "{p['glow']}", bg = "{p['selected']}", bold = true }}

[help]
border  = {{ fg = "{p['blue']}" }}
chord   = {{ fg = "{p['cyan']}" }}
action  = {{ fg = "{p['ice']}" }}
hovered = {{ fg = "{p['glow']}", bg = "{p['selected']}", bold = true }}

[filetype]
rules = [
	{{ mime = "**/image/*", fg = "{p['amber']}" }},
	{{ mime = "**/{{audio,video}}/*", fg = "{p['steel']}" }},
	{{ mime = "**/application/{{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}}", fg = "{p['coral']}" }},
	{{ mime = "**/application/{{pdf,doc,rtf}}", fg = "{p['cyan']}" }},
	{{ mime = "vfs/{{absent,stale}}", fg = "{p['dim']}" }},
	{{ url = "*", is = "orphan", fg = "{p['on_accent']}", bg = "{p['coral']}" }},
	{{ url = "*", is = "exec", fg = "{p['mint']}" }},
	{{ url = "*", is = "dummy", fg = "{p['on_accent']}", bg = "{p['coral']}" }},
	{{ url = "*/", is = "dummy", fg = "{p['on_accent']}", bg = "{p['coral']}" }},
	{{ url = "*/", fg = "{p['blue']}", bold = true }},
	{{ url = "*", fg = "{p['ice']}" }},
]
"""

# Scope → (colour key, fontStyle). Mirrors the Pi theme's syntax* slots.
TM_SCOPES = [
    ("comment, punctuation.definition.comment", "comment", ""),
    ("keyword, storage, storage.type, storage.modifier, keyword.other", "violet", ""),
    ("keyword.operator", "steel", ""),
    ("entity.name.function, support.function, meta.function-call entity.name.function", "cyan", ""),
    ("variable, variable.other, meta.definition.variable", "ice", ""),
    ("variable.parameter", "ice", "italic"),
    ("variable.other.member, variable.other.property, meta.property.object", "sky", ""),
    ("string, string.quoted, punctuation.definition.string", "mint", ""),
    ("constant.character.escape", "peach", ""),
    ("constant.numeric, constant.language, constant.character", "peach", ""),
    ("constant.other, variable.language, variable.other.constant, constant.other.symbol, support.constant", "amber", ""),
    ("entity.name.type, entity.name.class, support.type, support.class, entity.other.inherited-class, entity.name.namespace", "gold", ""),
    ("punctuation, meta.brace, punctuation.section, punctuation.separator, punctuation.terminator", "muted", ""),
    ("entity.name.tag, meta.tag", "blue", ""),
    ("entity.other.attribute-name", "gold", "italic"),
    ("markup.heading, entity.name.section", "glow", "bold"),
    ("markup.bold", "ice", "bold"),
    ("markup.italic", "steel", "italic"),
    ("markup.underline.link, string.other.link", "cyan", "underline"),
    ("markup.raw, markup.inline.raw, markup.fenced_code", "mint", ""),
    ("markup.quote", "steel", "italic"),
    ("markup.list punctuation.definition.list_item", "cyan", ""),
    ("markup.inserted, meta.diff.header.to-file", "mint", ""),
    ("markup.deleted, meta.diff.header.from-file", "coral", ""),
    ("markup.changed", "amber", ""),
    ("invalid, invalid.illegal", "coral", "bold"),
    ("invalid.deprecated", "amber", "italic"),
    ("meta.preprocessor, keyword.control.import, keyword.control.directive", "peach", ""),
    ("entity.name.label", "gold", ""),
]

def yazi_tmtheme(mode: str, p: dict) -> str:
    def setting(scope: str, key: str, style: str) -> str:
        font = f"\n\t\t\t\t<key>fontStyle</key>\n\t\t\t\t<string>{style}</string>" if style else ""
        return f"""\t\t<dict>
\t\t\t<key>scope</key>
\t\t\t<string>{escape(scope)}</string>
\t\t\t<key>settings</key>
\t\t\t<dict>
\t\t\t\t<key>foreground</key>
\t\t\t\t<string>{p[key]}</string>{font}
\t\t\t</dict>
\t\t</dict>"""

    body = "\n".join(setting(*s) for s in TM_SCOPES)
    return f"""<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!-- Butler {mode} — {escape(HEADER)} -->
<plist version="1.0">
<dict>
\t<key>name</key>
\t<string>Butler {mode.title()}</string>
\t<key>settings</key>
\t<array>
\t\t<dict>
\t\t\t<key>settings</key>
\t\t\t<dict>
\t\t\t\t<key>background</key>
\t\t\t\t<string>{p['bg']}</string>
\t\t\t\t<key>foreground</key>
\t\t\t\t<string>{p['ice']}</string>
\t\t\t\t<key>caret</key>
\t\t\t\t<string>{p['cyan']}</string>
\t\t\t\t<key>selection</key>
\t\t\t\t<string>{p['selected']}</string>
\t\t\t\t<key>lineHighlight</key>
\t\t\t\t<string>{p['deep']}</string>
\t\t\t</dict>
\t\t</dict>
{body}
\t</array>
</dict>
</plist>
"""

# ---------------------------------------------------------------- oh-my-posh
def omp(p: dict) -> str:
    tpl = json.loads((HERE / "omp.template.json").read_text())
    tpl["palette"] = {k: (p[v[1:]] if v.startswith("@") else v) for k, v in tpl["palette"].items()}
    return json.dumps(tpl, ensure_ascii=False, indent=1) + "\n"

# ---------------------------------------------------------------- delta
# delta 的语法主题只能选它内置的 bat 主题（自定义 tmTheme 需要装 bat 建缓存），
# 这里挑冷色调的两款，diff 标记、行号和 hunk 头则用 Butler 色。
DELTA_SYNTAX = {"dark": "Nord", "light": "GitHub"}

def delta(mode: str, p: dict) -> str:
    return f"""# Butler {mode} — {HEADER}
[delta]
    line-numbers = true
    side-by-side = false
    navigate = true
    syntax-theme = {DELTA_SYNTAX[mode]}
    features = decorations
    minus-style = syntax "{p['err_bg']}"
    minus-emph-style = syntax "{p['coral']}"
    plus-style = syntax "{p['ok_bg']}"
    plus-emph-style = syntax "{p['mint']}"
    line-numbers-minus-style = "{p['coral']}"
    line-numbers-plus-style = "{p['mint']}"
    line-numbers-zero-style = "{p['dim']}"
    line-numbers-left-style = "{p['line']}"
    line-numbers-right-style = "{p['line']}"
[delta "interactive"]
    keep-plus-minus-markers = true
[delta "decorations"]
    commit-decoration-style = "{p['blue']}" ol
    commit-style = raw
    file-style = omit
    hunk-header-decoration-style = "{p['blue']}" box
    hunk-header-file-style = "{p['glow']}"
    hunk-header-line-number-style = "{p['mint']}"
    hunk-header-style = file line-number syntax
"""

# ---------------------------------------------------------------- readability
def ghostty_opacity() -> float:
    """The window's `background-opacity` from the Ghostty config: the theme background is blended with whatever is behind the window."""
    try:
        return float(re.search(r"^background-opacity\s*=\s*([\d.]+)", (CFG / "ghostty/config").read_text(), re.M).group(1))
    except (OSError, AttributeError, ValueError):
        return 1.0

def blend(front: str, behind: str, alpha: float) -> str:
    return "#%02x%02x%02x" % tuple(round((f * alpha + b * (1 - alpha)) * 255) for f, b in zip(_rgb(front), _rgb(behind)))

def glass(bg: str, extreme: bool = False) -> list:
    """The theme background as seen through a translucent window: unchanged, and mixed with a dark and a light thing behind it. The default
    extremes (a dark-grey and a near-white window behind) are what a blurred desktop really offers; `extreme=True` uses pure black and white."""
    a = ghostty_opacity()
    dark, light = ("#000000", "#ffffff") if extreme else ("#303030", "#f0f0f0")
    return [bg, blend(bg, dark, a), blend(bg, light, a)]

def _rgb(h: str):
    h = h.lstrip("#")
    return [int(h[i:i + 2], 16) / 255 for i in (0, 2, 4)]

def luminance(h: str) -> float:
    r, g, b = (c / 12.92 if c <= 0.03928 else ((c + 0.055) / 1.055) ** 2.4 for c in _rgb(h))
    return 0.2126 * r + 0.7152 * g + 0.0722 * b

def contrast(a: str, b: str) -> float:
    hi, lo = sorted((luminance(a), luminance(b)), reverse=True)
    return (hi + 0.05) / (lo + 0.05)

PAL = {mode: derive(RAW[mode]) for mode in ("dark", "light")}

def _lin(c: float) -> float:
    return c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4

def _gamma(c: float) -> float:
    return 12.92 * c if c <= 0.0031308 else 1.055 * c ** (1 / 2.4) - 0.055

def to_oklch(h: str):
    r, g, b = (_lin(c) for c in _rgb(h))
    l, m, s = (0.4122214708 * r + 0.5363325363 * g + 0.0514459929 * b, 0.2119034982 * r + 0.6806995451 * g + 0.1073969566 * b, 0.0883024619 * r + 0.2817188376 * g + 0.6299787005 * b)
    l, m, s = (x ** (1 / 3) for x in (l, m, s))
    L, A, B = 0.2104542553 * l + 0.7936177850 * m - 0.0040720468 * s, 1.9779984951 * l - 2.4285922050 * m + 0.4505937099 * s, 0.0259040371 * l + 0.7827717662 * m - 0.8086757660 * s
    return L, (A * A + B * B) ** 0.5, math.atan2(B, A)

def from_oklch(L: float, C: float, hue: float):
    """sRGB hex for the colour, or None when it falls outside the gamut."""
    A, B = C * math.cos(hue), C * math.sin(hue)
    l, m, s = (L + 0.3963377774 * A + 0.2158037573 * B) ** 3, (L - 0.1055613458 * A - 0.0638541728 * B) ** 3, (L - 0.0894841775 * A - 1.2914855480 * B) ** 3
    rgb = (4.0767416621 * l - 3.3077115913 * m + 0.2309699292 * s, -1.2684380046 * l + 2.6097574011 * m - 0.3413193965 * s, -0.0041960863 * l - 0.7034186147 * m + 1.7076147010 * s)
    if any(c < -1e-4 or c > 1 + 1e-4 for c in rgb):
        return None
    return "#%02x%02x%02x" % tuple(round(min(1.0, max(0.0, _gamma(max(c, 0.0)))) * 255) for c in rgb)

def fit(color: str, backgrounds: list, minimum: float = 4.5, chroma: float = 0.0) -> str:
    """Keep the hue and the colourfulness, move only the lightness (OKLCH, so the colour does not turn electric or grey as it darkens) away from
    the backgrounds until the text reads on every one of them (WCAG ratio). `chroma` is a floor for coloured text; colours that do not fit the screen
    gamut at a lightness give up some chroma first."""
    L, C, hue = to_oklch(color)
    C = max(C, chroma)
    toward_light = sum(luminance(x) for x in backgrounds) / len(backgrounds) < 0.2
    out = color
    for _ in range(400):
        c = C
        while c > 0:
            out = from_oklch(L, c, hue)
            if out:
                break
            c -= 0.004
        else:
            out = from_oklch(L, 0.0, hue)
        if out and all(contrast(out, bg) >= minimum for bg in backgrounds):
            return out
        L = min(1.0, L + 0.004) if toward_light else max(0.0, L - 0.004)
    return out or color

# Levels of text, each its own step so hierarchy survives: the main text is far above the gate, notes sit just above it.
LEVELS = {"text": 7.0, "subtext": 6.0, "muted": 5.2, "note": 4.8, "colour": 4.8}
VIVID = 0.07

# ---------------------------------------------------------------- Ghostty
def ghostty(mode: str, p: dict) -> str:
    """A terminal theme. Text is fitted on the background and on its worst cases through the window's transparency (black or white behind);
    coloured text keeps its saturation, the grey `bright black` stays a visible note colour (the gate in `--check` is 4.5:1, WCAG AA)."""
    bg = glass(p["bg"])
    hue = lambda c, level="colour": fit(c, bg, LEVELS[level], VIVID)
    grey = lambda c, level: fit(c, bg, LEVELS[level])
    bright = lambda c: fit(c, bg, LEVELS["colour"], 0.12)
    ansi = [p["ice"] if luminance(p["bg"]) > 0.5 else p["selected"], hue(p["coral"]), hue(p["mint"]), hue(p["gold"]), hue(p["sky"]), hue(p["violet"]), hue(p["cyan"]),
            grey(p["steel"], "muted"), grey(p["comment"], "note"),
            bright(p["coral"]), bright(p["mint"]), bright(p["gold"]), bright(p["lavender"]), bright(p["violet"]), bright(p["glow"]),
            grey(p["ice"], "text")]
    lines = [f"# Butler {mode} — {HEADER}", f"background = {p['bg']}", f"foreground = {grey(p['ice'], 'text')}", f"cursor-color = {hue(p['cyan'])}", f"cursor-text = {p['bg']}",
             f"selection-background = {p['selected']}", f"selection-foreground = {fit(p['ice'], [p['selected']], 7.0)}"]
    lines += [f"palette = {i}={c}" for i, c in enumerate(ansi)]
    return "\n".join(lines) + "\n"

# ---------------------------------------------------------------- herdr
def herdr_tokens(p: dict) -> dict:
    """herdr colour tokens, one hue per place so the chrome is not a single colour: tab chip = accent (cyan), section headings and bullets = overlay0
    (violet), inactive items = subtext0 (sky), tab labels = overlay1 (mint), the selected item = text (the lightest), and the agent states take the other
    colours. The focused tab's label is drawn in `surface_dim` on the accent (herdr uses it as the chip text while panel_bg is `reset`), so it is
    the theme background, never `reset` (that would be the terminal's own foreground on the accent). The sidebar, the tab strip and the panes use `reset` (the terminal's own background), so Ghostty's transparency and blur show through;
    only the selected row has a colour of its own (Ghostty keeps cells with an explicit background opaque). Text is fitted on the terminal background
    as seen through the glass, and on the selected row."""
    active = blend(p["violet"], p["selected"], 0.10)
    surfaces = glass(p["bg"]) + [active]
    hue = lambda c: fit(c, surfaces, LEVELS["colour"], VIVID)
    return {"accent": hue(p["cyan"]), "panel_bg": "reset", "sidebar_bg": "reset", "active_row_bg": active, "selection_bg": active,
            "surface0": p["panel"], "surface1": p["line"], "surface_dim": p["bg"], "overlay0": hue(p["violet"]), "overlay1": hue(p["mint"]),
            "text": fit(p["ice"], surfaces, LEVELS["text"]), "subtext0": hue(p["sky"]), "mauve": hue(p["violet"]), "green": hue(p["mint"]), "yellow": hue(p["gold"]),
            "red": hue(p["coral"]), "blue": hue(p["sky"]), "teal": hue(p["glow"]), "peach": hue(p["peach"])}

HERDR_BEGIN = "# >>> butler theme (generated by ~/.config/theme/butler/generate.py; edit palette.json, not this block)"
HERDR_END = "# <<< butler theme"

def herdr_block() -> str:
    out = [HERDR_BEGIN, "[theme]", 'name = "rose-pine-dawn"', "auto_switch = true", 'light_name = "rose-pine-dawn"', 'dark_name = "rose-pine"']
    for mode in ("light", "dark"):
        out += ["", f"[theme.custom.{mode}]"] + [f'{k} = "{v}"' for k, v in herdr_tokens(PAL[mode]).items()]
    out.append(HERDR_END)
    return "\n".join(out) + "\n"

def write_herdr_theme() -> None:
    """Replace the generated block in herdr's config.toml; the first time, replace the hand-written [theme] table with it."""
    path = CFG / "herdr/config.toml"
    text = path.read_text()
    if HERDR_BEGIN in text:
        text = re.sub(re.escape(HERDR_BEGIN) + r".*?" + re.escape(HERDR_END) + r"\n", lambda _: herdr_block(), text, flags=re.S)
    else:
        text = re.sub(r"\[theme\]\n.*?(?=\n\[|\Z)\n?", "", text, flags=re.S).rstrip() + "\n\n" + herdr_block()
    path.write_text(text)
    print("wrote", path)

# ---------------------------------------------------------------- Pi (Butler UI themes)
PI_TEXT = ("ice", "cyan", "glow", "blue", "steel", "muted", "dim", "mint", "amber", "coral", "violet", "gold", "sky", "lavender", "peach")
PI_ROLES = {
    "accent": "cyan", "border": "sky", "borderAccent": "violet", "borderMuted": "line", "success": "mint", "error": "coral", "warning": "amber",
    "muted": "muted", "dim": "dim", "text": "ice", "thinkingText": "lavender", "scrollbarTrack": "line", "scrollbarThumb": "steel",
    "userMessageText": "ice", "customMessageText": "ice", "customMessageLabel": "violet", "toolTitle": "sky", "toolOutput": "muted",
    "mdHeading": "gold", "mdLink": "sky", "mdLinkUrl": "dim", "mdCode": "mint", "mdCodeBlock": "ice", "mdCodeBlockBorder": "line", "mdQuote": "lavender",
    "mdQuoteBorder": "violet", "mdHr": "line", "mdListBullet": "amber", "toolDiffAdded": "mint", "toolDiffRemoved": "coral", "toolDiffContext": "muted",
    "syntaxComment": "dim", "syntaxKeyword": "violet", "syntaxFunction": "sky", "syntaxVariable": "ice", "syntaxString": "mint", "syntaxNumber": "peach",
    "syntaxType": "gold", "syntaxOperator": "cyan", "syntaxPunctuation": "muted", "thinkingOff": "line", "thinkingMinimal": "dim", "thinkingLow": "steel",
    "thinkingMedium": "sky", "thinkingHigh": "cyan", "thinkingXhigh": "glow", "thinkingMax": "violet", "bashMode": "amber",
    "selectedBg": "selected", "userMessageBg": "panel", "customMessageBg": "deep", "toolPendingBg": "panel", "toolSuccessBg": "ok_bg", "toolErrorBg": "err_bg",
}

def pi_vars(p: dict) -> dict:
    """The colour vocabulary of a Pi theme: text colours are fitted to the terminal background (also through the glass) and to the panels they sit on."""
    surfaces = glass(p["bg"]) + [p["panel"], p["deep"]]
    out = {name: fit(p[name], surfaces, LEVELS["text"] if name == "ice" else LEVELS["colour"], 0.0 if name in ("ice", "steel", "muted", "dim") else VIVID) for name in PI_TEXT}
    out.update({name: p[name] for name in ("line", "panel", "deep", "selected", "ok_bg", "err_bg")})
    return out

def write_pi_theme(mode: str, p: dict) -> None:
    path = Path(os.environ.get("BUTLER_PI", os.path.expanduser("~/Devs/.worktrees/butler-code/pi-firecode"))) / "themes" / ("butler.json" if mode == "light" else "butler-dark.json")
    if not path.is_file():  # no Pi package checkout on this machine: nothing to update
        return
    theme = json.loads(path.read_text())
    theme["vars"] = pi_vars(p)
    keep = {k: v for k, v in theme["colors"].items() if k in ("searchMatchBg", "searchMatchText")}
    theme["colors"] = {**{k: v for k, v in PI_ROLES.items()}, **keep}
    path.write_text(json.dumps(theme, ensure_ascii=False, indent=2) + "\n")
    print("wrote", path)

# ---------------------------------------------------------------- nvim
# 注释和行号刻意比正文淡，所以只给它们 3.8，其余语法色按 4.8 调。
NVIM_TEXT = {"ice": LEVELS["text"], "steel": LEVELS["muted"], "muted": LEVELS["muted"], "dim": 3.8, "comment": 3.8}
NVIM_ACCENTS = ("cyan", "glow", "blue", "sky", "lavender", "mint", "amber", "coral", "violet", "gold", "peach")

def nvim_vars(mode: str, p: dict) -> dict:
    """Light theme only: its syntax colours are too pale on the light glass, so fit them to the window background (also through the glass) and the
    cursor-line surface. The dark theme is already readable and stays as the palette defines it."""
    if mode == "dark":
        return p
    surfaces = glass(p["bg"]) + [p["deep"]]
    out = dict(p)
    for name, minimum in NVIM_TEXT.items():
        out[name] = fit(p[name], surfaces, minimum)
    for name in NVIM_ACCENTS:
        out[name] = fit(p[name], surfaces, LEVELS["colour"], VIVID)
    return out

def nvim_palette() -> str:
    def lua_table(p: dict) -> str:
        return "{\n" + "".join(f"\t\t{k} = \"{v}\",\n" for k, v in p.items()) + "\t}"

    return f"""-- Butler palette — {HEADER}
return {{
\tdark = {lua_table(nvim_vars('dark', PAL['dark']))},
\tlight = {lua_table(nvim_vars('light', PAL['light']))},
}}
"""

def check() -> int:
    """Readability gate, no files written: every text colour of the Ghostty and herdr themes must reach 4.5:1 on what it is drawn on."""
    bad = 0
    for mode in ("dark", "light"):
        p = PAL[mode]
        theme = ghostty(mode, p)
        get = lambda key: re.search(rf"^{key} = (#\w+)$", theme, re.M).group(1)
        pairs = [("selection text", get("selection-foreground"), get("selection-background"), 7.0)]
        for behind in glass(p["bg"]):
            pairs.append((f"foreground over {behind}", get("foreground"), behind, 7.0 if behind == p["bg"] else 4.5))
            pairs.append((f"cursor over {behind}", get("cursor-color"), behind, 4.5))
            pairs += [(f"ansi {i} over {behind}", c, behind, 4.5) for i, c in enumerate(re.findall(r"palette = \d+=(#\w+)", theme)) if i != 0]
        tokens = herdr_tokens(p)
        surfaces = {f"glass {bg}": bg for bg in glass(p["bg"])} | {"active_row_bg": tokens["active_row_bg"]}
        for name in ("accent", "overlay0", "overlay1", "text", "subtext0", "mauve", "green", "yellow", "red", "blue", "teal", "peach"):
            pairs += [(f"herdr {name} on {s}", tokens[name], bg, 4.5) for s, bg in surfaces.items()]
        surfaces_pi = glass(p["bg"]) + [p["panel"], p["deep"]]
        pairs += [(f"pi {name} on {bg}", color, bg, 4.5) for name, color in pi_vars(p).items() if name in PI_TEXT for bg in surfaces_pi]
        worst = min(contrast(a, b) for _, a, b, _ in pairs)
        for name, a, b, need in pairs:
            if contrast(a, b) < need:
                bad += 1
                print(f"  too faint [{mode}] {name}: {a} on {b} = {contrast(a, b):.2f} (needs {need})")
        print(f"{mode}: {len(pairs)} text colours checked, lowest contrast {worst:.2f}")
    return 1 if bad else 0

def main() -> None:
    for mode in ("dark", "light"):
        p = PAL[mode]
        write(CFG / "tmux/themes" / f"butler-{mode}.conf", tmux(mode, p))
        flavor = CFG / "yazi/flavors" / f"butler-{mode}.yazi"
        write(flavor / "flavor.toml", yazi_flavor(mode, p))
        write(flavor / "tmtheme.xml", yazi_tmtheme(mode, p))
        write(CFG / "oh-my-posh" / f"butler_{mode}.omp.json", omp(p))
        write(CFG / "git" / f"delta-{mode}.gitconfig", delta(mode, p))
        write(CFG / "ghostty/themes" / f"butler-{mode}", ghostty(mode, p))
        write_pi_theme(mode, p)
    write(CFG / "nvim/lua/butler/palette.lua", nvim_palette())
    write_herdr_theme()

if __name__ == "__main__":
    sys.exit(check()) if "--check" in sys.argv else main()
